{
 "title": "PS2 Barnacle Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "frameHeight",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "res_y", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "frameWidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "res_x", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "targetBitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "targetBitrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "bitrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "encodeFPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "encodeFps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WebRTC FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "PixelStreaming2_WebRTC_Fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "jitter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quantization Parameter (QP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "qp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EncoderMinQuality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "PixelStreaming2_Encoder_MinQuality",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EncoderMaxQuality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "PixelStreaming2_Encoder_MaxQuality",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "encodeTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "encodeTime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packets Lost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "packetsLost", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "memory_physical", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "memory_gpu", "legendFormat": "__auto" }
   ]
  }
 ]
}