{
 "title": "Unreal Engine Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Average FPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(mean_fps[2s])) / sum(count_over_time(mean_fps[2s]))",
     "legendFormat": "Average FPS"
    }
   ]
  },
  {
   "title": "Individual FPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mean_fps", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "VRAM Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "memory_gpu", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Virtual Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "memory_virtual", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Physical Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "memory_physical", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Game Thread Time (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "mean_gamethreadtime", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Render Thread Time (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "mean_rendertime", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Frame Time (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "mean_frametime", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "Hung Frame Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "num_hangs", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "GPU Time (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "mean_gputime", "legendFormat": "ID: {{id}}" }
   ]
  },
  {
   "title": "RHI Thread Time (MS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "mean_rhithreadtime", "legendFormat": "ID: {{id}}" }
   ]
  }
 ]
}